version: '3.8'
services:
  fossgis-nginx:
    build:
      context: fossgis-nginx/
    ports:
      - 8000:80
    depends_on:
      - fossgis-postgis
      - fossgis-geoserver
  fossgis-geoserver:
    image: terrestris/geoserver:2.22.2
    ports:
      - 8080:8080
    volumes:
      - ./fossgis-geoserver/geoserver_data:/opt/geoserver_data/:Z
    environment:
      - EXTRA_JAVA_OPTS=-Xms1g -Xmx2g
    depends_on:
      - fossgis-postgis
  fossgis-postgis:
    image: postgis/postgis:15-3.3-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./fossgis-postgis/postgresql_data:/var/lib/postgresql/data:Z
