version: '3.8'
services:
  fossgis-geoserver:
    image: docker.osgeo.org/geoserver:2.24.2
    ports:
      - 8080:8080
  fossgis-postgis:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: fossgis
      POSTGRES_PASSWORD: fossgis
